inspirehep/beard

beard/clustering/__init__.py
beard/clustering/blocking.py
beard/clustering/tests/test_blocking.py
beard/metrics/clustering.py

This PR implements blocking on top of clustering estimators.

clustering: blocking for clustering estimators

---

beard/clustering/__init__.py
beard/clustering/tests/test_wrappers.py
beard/clustering/wrappers.py

This PR implements a scikit-learn compatible wrapper for Scipy's hiearchical clustering.

clustering: wrapper for Scipy's hiearchical clustering

---

beard/metrics/clustering.py
beard/metrics/tests/test_text.py
beard/metrics/text.py

* A new file was created that will be used for string distance metrics.
* Substring_occurences was created that returns a generator with the
occurences of a string.
* Jaro matching was implemented to calculate the matching characters
based on the Jaro metric algorithm
* Tests were developed for the aforementioned features

metrics: jaro distance metric

---

beard/clustering/tests/test_blocking.py
beard/similarity/__init__.py
beard/similarity/pairs.py
beard/similarity/tests/test_pairs.py
beard/utils/__init__.py
beard/utils/strings.py
beard/utils/tests/test_strings.py
beard/utils/tests/test_transformers.py
beard/utils/transformers.py

This PR implements transformers for paired data.

similarity: transformers for paired data

---

beard/similarity/__init__.py
beard/similarity/pairs.py
beard/similarity/tests/test_pairs.py

Signed-off-by: Hussein <h.natsheh@ciapple.com>

Jaccard similarity for paired data

---

beard/ext/__init__.py
beard/ext/metaphone.py
beard/utils/names.py
beard/utils/strings.py
beard/utils/tests/test_names.py
pytest.ini
setup.py

* Provides a tokenizing function for future blocking algorithm.

utils: name tokenization

---

beard/clustering/tests/test_wrappers.py
beard/clustering/wrappers.py
beard/metrics/__init__.py
beard/metrics/clustering.py

clustering: custom scoring functions

---

beard/metrics/clustering.py

metrics: faster implementation of b3 scoring metrics

---

.travis.yml
travis-install.sh

See http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/

general: no sudo with Travis

---

examples/applications/author-disambiguation/clustering.py
examples/applications/author-disambiguation/distance.py

author disambiguation: improve Python 3 compatibility

---

examples/applications/author-disambiguation/clustering.py
examples/applications/author-disambiguation/distance.py
examples/applications/author-disambiguation/utils.py

examples: lighter coauthors extraction

---

beard/metrics/clustering.py

metrics: fix misspelling (closes #60)

---

beard/clustering/blocking_funcs.py
tests/clustering/test_block.py
tests/clustering/test_blocking_funcs.py

clustering: simplified double_metaphone blocking

---

beard/clustering/blocking.py
setup.py
tests/clustering/test_blocking.py

* Gets rid of Joblib
* Removes feature of passing negative value of n_jobs.

clustering: new parallelization implementation

---

beard/clustering/blocking.py

clustering: better way to finish processes.

---

examples/applications/author-disambiguation/clustering.py
examples/applications/author-disambiguation/distance.py
examples/applications/author-disambiguation/utils.py

examples: removal of references feature

---

examples/applications/author-disambiguation/clustering.py

applications: fix json dumping error

---

beard/utils/misc.py
beard/utils/names.py
tests/utils/test_names.py

utils: better name normalization (closes #20)

---

beard/clustering/blocking.py
beard/clustering/blocking_funcs.py
beard/similarity/__init__.py
beard/similarity/pairs.py
beard/utils/__init__.py
beard/utils/names.py
examples/applications/author-disambiguation/clustering.py
examples/applications/author-disambiguation/distance.py
examples/applications/author-disambiguation/utils.py
setup.py
tests/similarity/test_pairs.py
tests/utils/test_names.py

examples: new name features

---

beard/clustering/__init__.py
beard/clustering/blocking_funcs.py
beard/utils/__init__.py
beard/utils/names.py
examples/applications/author-disambiguation/sampling.py
setup.py
tests/clustering/test_blocking_funcs.py
tests/utils/test_names.py

* Allows to use nysiis and soundex algorithms
for blocking when using Python 2.
* Introduces a dependency for Python 2 only.

clustering: generalization of phonetic blocking

---

examples/applications/author-disambiguation/clustering.py

* Allows to dump result to a file.
* Allows to pass train set.

applications: benchmarking setup

---

beard/clustering/wrappers.py
examples/applications/author-disambiguation/README.rst
examples/applications/author-disambiguation/clustering.py
examples/applications/author-disambiguation/distance.py
examples/applications/author-disambiguation/sampling.py
examples/applications/author-disambiguation/utils.py

This is a PR to make sure everything is ready for production.

[WIP] Prepare code for production

---

beard/clustering/blocking.py

* Removes multiprocessing for n_jobs = 1.
Signed-off-by: Grzegorz Jacenków <grzegorz.jacenkow@cern.ch>

blocking: multiprocessing

---

examples/applications/author-disambiguation/clustering.py
examples/applications/author-disambiguation/sampling.py

Signed-off-by: Mateusz Susik <mateuszsusik@gmail.com>

examples: Python 3 compability

---

beard/similarity/__init__.py
beard/similarity/pairs.py
examples/applications/author-disambiguation/distance.py

Signed-off-by: Mateusz Susik <mateuszsusik@gmail.com>

similarity: threshold transformer

---

.gitignore
.travis.yml
MANIFEST.in
pytest.ini
run-tests.sh
setup.py
travis-install.sh

general: prepare for release on PyPI

---

beard/__init__.py

Convenience commit for the 0.2 tag.

general: release 0.2
